// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thsfmvmbhhpugoofcfhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoc2Ztdm1iaGhwdWdvb2ZjZmh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzQyNjQsImV4cCI6MjA1OTk1MDI2NH0.jrvZAwYEGYK88IiwxgIOgcUe9fBpY1dnXxsgdTP-NWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);