// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckeecisqdqbrbwjtmirz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZWVjaXNxZHFicmJ3anRtaXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDk1OTUsImV4cCI6MjA1OTg4NTU5NX0.k2p36f_nyQFXi-DfhvFU1eB8Qd_xJ5kKG8vTujwvivA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);